### ISSUE TITLE
NPM incorrect URL

### ISSUE THREAD

**Issue by wiserweb** [jidan70/openstack-swift-client-region#1]
It appears that your npm package (https://www.npmjs.com/package/openstack-swift-client-region) is pointing to  https://github.com/stefanodefaria/swift-client instead of https://github.com/jidan70/openstack-swift-client-region.

**Comment by jidan70** [comment]
Thanks, fixed in #https://github.com/jidan70/openstack-swift-client-region/commit/03c65a002fb4034344fc03489482a804599a6145
